### ISSUE TITLE
Improve waiting queue

### ISSUE THREAD

**Issue by hotzenklotz** [Bartzi/LabShare#60]
It would be great that if I could  see who is queued before me. Currently  I can only see the current active user and the next one but not who comes after them. This feature only makes sense if there are 3+ people queued up.
Perhaps there could be a little tooltip when I hover of the queue/next row?

![image](https://cloud.githubusercontent.com/assets/1105056/23901165/4cbb287c-08bc-11e7-8b46-c98dd0b4da92.png)

**Comment by Bartzi** [comment]
closing this since we do not use the system for reservation management anymore.
